version: "3"
services:
  redis:
    image: "redis:alpine"

    # Remove the port mapping when I deploy to production so that redis is not
    # exposed to outside world
    ports:
      - "6666:6379"
    expose:
      - 6379
    restart: always

  dev:
    image: node:14
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install && npm run dev"
    ports:
      - 3000:3000
    expose:
      - 3000
      - 80
